name: Auto Renew NYT Pass

on:
  schedule:
    - cron: '0 13 * * *' # Runs at 6am LA time
  workflow_dispatch:

jobs:
  renew-pass:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Renewal Script
        env:
          # We now pass 4 secrets instead of 2
          LIBRARY_CARD: ${{ secrets.LIBRARY_CARD }}
          LIBRARY_PIN: ${{ secrets.LIBRARY_PIN }}
          NYT_EMAIL: ${{ secrets.NYT_EMAIL }}
          NYT_PASSWORD: ${{ secrets.NYT_PASSWORD }}
        run: python main.py